; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[ctools][version] = "1.2"

projects[ckeditor][version] = "1.9"

projects[context][version] = "3.0-beta4"

projects[devel][version] = "1.3"

projects[features][version] = "1.0"

projects[fontyourface][version] = "2.4"

projects[imce][version] = "1.5"

projects[nice_menus][version] = "2.1"

projects[panels][version] = "3.3"

projects[panels_breadcrumbs][version] = "1.6"

projects[pathauto][version] = "1.2"

projects[token][version] = "1.2"

projects[views][version] = "3.5"

; Themes
projects[omega][version] = "3.1"

